FROM jboss/wildfly

COPY deployments/root.war /opt/jboss/wildfly/standalone/deployments/root.war

# docker build -t cjoakim/azure-webapp-wildfly .
# docker run -d -e xxx=yyy -p 8080:8080 cjoakim/azure-webapp-wildfly:latest
# Invoke http://localhost:8080/
